
import Link from 'next/link';
import { supabase } from '@/lib/supabase';

export const revalidate = 0;

export default async function Home() {
  const { data: haberler, error } = await supabase
      .from('haberler')
          .select('*')
              .order('created_at', { ascending: false });

                if (error) {
                    console.error('Haberler çekilirken hata oluştu:', error);
                      }

                        return (
                            <main className="min-h-screen bg-gray-50 py-10 px-4 sm:px-6 lg:px-8">
                                  <div className="max-w-4xl mx-auto">
                                          <h1 className="text-3xl font-extrabold text-gray-900 mb-2 text-center">
                                                    Son Haberler
                                                            </h1>
                                                                    <p className="text-gray-500 text-center mb-8 text-sm">
                                                                              Detayını okumak istediğiniz habere tıklayın.
                                                                                      </p>

                                                                                              <div className="grid gap-6">
                                                                                                        {haberler && haberler.length > 0 ? (
                                                                                                                    haberler.map((item: any) => (
                                                                                                                                  <Link
                                                                                                                                                  key={item.id}
                                                                                                                                                                  href={`/haber/${item.id}`}
                                                                                                                                                                                  className="bg-white rounded-xl border border-gray-200 shadow-sm hover:shadow-md transition duration-200 overflow-hidden flex flex-col sm:flex-row group"
                                                                                                                                                                                                >
                                                                                                                                                                                                                {item.resim_url && (
                                                                                                                                                                                                                                  <div className="sm:w-48 h-48 flex-shrink-0 bg-gray-100">
                                                                                                                                                                                                                                                      <img
                                                                                                                                                                                                                                                                            src={item.resim_url}
                                                                                                                                                                                                                                                                                                  alt={item.baslik}
                                                                                                                                                                                                                                                                                                                        className="w-full h-full object-cover group-hover:scale-105 transition duration-300"
                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                              )}

                                                                                                                                                                                                                                                                                                                                                                                              <div className="p-6 flex flex-col justify-between flex-grow">
                                                                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                    {item.kategori && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="inline-block px-2.5 py-0.5 rounded-full text-xs font-semibold bg-blue-100 text-blue-800 mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {item.kategori}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2 className="text-lg font-bold text-gray-900 group-hover:text-blue-600 transition mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {item.baslik}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex items-center justify-between text-xs text-gray-400 mt-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {item.created_at
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ? new Date(item.created_at).toLocaleDateString('tr-TR')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        : ''}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="text-blue-600 font-medium">Devamını Oku →</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-center text-gray-500">Henüz haber bulunmuyor.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                